### PR TITLE
Read only root fs

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards: https://github.com/giantswarm/giantswarm/issues/31179

This PR ensures file system is accessed with root only

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by TheoBrigitte — CHANGES_REQUESTED** [review]
This should be fine, but I would prefer that this is tested with the alloy logging setup to ensure things continue to work as expected.

**Comment by QuentinBisson** [comment]
Similar grafana agent PR tested here https://github.com/giantswarm/grafana-agent-app/pull/73

**Comment by TheoBrigitte** [comment]
> @TheoBrigitte can you take care of testing this change? Because I'm not sure what's the state of alloyLogs

You can test this on `garfish` where its already running, you would need to deploy the new version of the app and monitor:
- `alloy-logs` logs: for any error, using `kubectl logs` should be enough
- `alloy-logs` pods resources: to ensure resource usage stays the same, you can use the ` Kubernetes / Compute Resources / Pod` dashboard for this.
- The amount of logs received on Loki. You can use the following query  `sum(rate({scrape_job=~".+", cluster_id="golem"} [1m]))by(scrape_job)` which count the amount of log lines received for each scrape job.

**Comment by QuentinBisson** [comment]
But I found out I cannot because security context and others are configured in the logging operator :D

**Comment by QuentinBisson** [comment]
So this PR works quite fine with alloy rules for instances :)

**Comment by QuentinBisson** [comment]
@TheoBrigitte could you take another look at this? This only sets readonlyrootfs and does not change the resource usage at all :)

**Comment by TheoBrigitte** [comment]
Have you tested this with Alloy for logs ?

**Comment by QuentinBisson** [comment]
Yes :)

**Review by QuantumEnigmaa — APPROVED** [review]
LGTM.
Nice to have more security :)

**Review by TheoBrigitte — APPROVED** [review]

**Pull request merged**
