### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by taylorbot**
Towards: https://github.com/giantswarm/roadmap/issues/3522

Merge after https://github.com/giantswarm/alloy-app/pull/29

### CODE REVIEW

**Review by TheoBrigitte — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Is there any specific reason why you want to go with 1.0.0?

**Comment by TheoBrigitte** [comment]
> Is there any specific reason why you want to go with 1.0.0? This has semver implications that i'm not sure we need yet?

There are some breaking changes introduced with this as listed in the changelog. The rules for semver says that whenever a breaking changes occurs we should bump the major version.

**Comment by QuentinBisson** [comment]
That is unless we are using major version 0 😅

**Comment by TheoBrigitte** [comment]
Alright let's have a minor then.

**Pull request closed without merging**
